CREATE DATABASE inlock_games_tarde;
GO

USE inlock_games_tarde;
GO
 
 CREATE TABLE ESTUDIO(
 idEstudio SMALLINT PRIMARY KEY IDENTITY ,
 nomeEstudio VARCHAR(40) NOT NULL,
 );
 GO

 CREATE TABLE JOGO (
 idJogo SMALLINT PRIMARY KEY IDENTITY,
 idEstudio SMALLINT FOREIGN KEY REFERENCES ESTUDIO (idEstudio),
 nomeJogo VARCHAR(50) NOT NULL,
 descricao VARCHAR(100) NOT NULL,
 dataLancamento DATETIME NOT NULL,
 valor VARCHAR(40) NOT NULL
 );
 GO

CREATE TABLE TIPOUSUARIO(
idTipoUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
titulo VARCHAR(40) NOT NULL
);
GO

CREATE TABLE USUARIO(
idUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
idTipoUsuario SMALLINT FOREIGN KEY REFERENCES TIPOUSUARIO (idTipoUsuario),
email VARCHAR(150) NOT NULL UNIQUE,
senha VARCHAR(20) NOT NULL,
);
GO